### ISSUE TITLE
workshop-1 Participate

### ISSUE THREAD

**Issue by Jonny621** [newtonproject/workshop#1]
Add a comment with your email to attend the workshop.

**Comment by Jonny621** [comment]
Apply to join. piaoyu@diynova.com

**Comment by xiawu** [comment]
apply: xiawu at zeuux dot org

**Comment by yangyansong23** [comment]
Apply to join. yangyansong@diynova.com

**Comment by shuweicn** [comment]
Apply to join.  shuweicn@gmail.com

**Comment by jiangtao-tang** [comment]
Apply to join.

**Comment by gjw00001** [comment]
Apply to join. gjw00001@126.com
